#name: CI and remote deploy (SSH password)
#
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install deps & build
#        run: |
#          npm ci
#          npm run build
#
#      - name: Copy build to server (using sshpass)
#        env:
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
#          SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
#        run: |
#          sudo apt-get update && sudo apt-get install -y sshpass
#          sshpass -p "$SSH_PASSWORD" scp -P $SSH_PORT -r ./build "$SSH_USER@$SSH_HOST:/var/www/myapp"
#          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT "$SSH_USER@$SSH_HOST" "sudo systemctl restart myapp.service"

name: Hello to On-Prem

on:
  workflow_dispatch: # 수동 실행 버튼

permissions:
  contents: read

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: SSH and create helloworld
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
#          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e
            mkdir -p /tmp/ga-test
            echo "hello from GitHub Actions @ $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > /tmp/ga-test/helloworld.txt
            ls -al /tmp/ga-test
            echo "---- file content ----"
            cat /tmp/ga-test/helloworld.txt
            echo "----------------------"
